version: '3.8'
services:
  db:
    container_name: autospace_db
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '2010:5432'
    volumes:
      - db_data_autospace:/var/lib/postgresql/data
volumes:
  db_data_autospace:
